---
- hosts: server_nginx
  tasks:
    - name: Pull latest configuration
      become: yes
      shell: |
        cd /etc/nginx/vhost
        git pull
      args:
        chdir: /etc/nginx/vhost
      register: git_pull_output

    - debug:
        var: git_pull_output.stdout_lines

    - name: Verify Nginx config
      become: yes
      command: nginx -t
      changed_when: false

    - name: Reload config
      become: yes
      command: nginx -s reload
      changed_when: true      