---
- hosts: server_nginx
  tasks:
    - name: Verify Nginx config
      become: yes
      command: nginx -t
      changed_when: false

    - name: Pull latest configuration
      become: yes
      command: "cd /etc/nginx/vhost && git pull"
      changed_when: true
