---
- hosts: server_nginx
  tasks:
    - name: Pull latest configuration
      become: yes
      shell: |
        cd /etc/nginx/vhost
        git pull
      args:
        chdir: /etc/nginx/vhost
      register: git_pull_output

    - debug:
        var: git_pull_output.stdout_lines

    - name: Xác minh config nginx
      become: yes
      shell: nginx -t
      changed_when: false
      register: verify_nginx

    - debug:
        msg: "{{ verify_nginx.stderr_lines  }}"

    - name: Reload lại config
      become: yes
      command: nginx -s reload
      changed_when: true      

    - name: Display the config
      debug:
        msg: "Done !!"