---
- hosts: server_nginx
  tasks:
    - name: Print message
      debug:
        msg: Hello Ansible World

    - name: Verify Nginx config
      become: yes
      command: nginx -t
      changed_when: false
